show databases;
create database customer_behaviour;
use customer_behaviour;

select * from customer
order by customer_id desc;


-- Q1.Whats the total revenue generated by male vs female customers?

select gender,count(customer_id) as customers,sum(purchase_amount) as revenue, 
round((100 *sum(purchase_amount)/(select sum(purchase_amount) from customer)),2) as percent
from customer
group by gender
-- Conclusion: Revenue mostly comes from male customers with 67% of total revenue


-- Q2. Which customers used discount but still spend over average purchase amount?

select customer_id, purchase_amount
from customer 
where purchase_amount >= (select avg(purchase_amount) from customer)
and discount_applied='yes';
-- Conclusion: Shown Customer Ids of required


-- Q3. Top 5 products with highest avg review rating
select item_purchased,round(avg(review_rating),2) as avg_review
from customer 
-- where review_rating>=(select avg(review_rating) from customer) --wrong since it will exclude values below avg before agg
group by item_purchased
order by avg_review desc
limit 5;
-- Conclusion: Gloves,Sandals, Boots, Hat, Handbag


-- Q4. avg purchase amount btwn std vs express delivery
select distinct shipping_type from customer;
select shipping_type,round(avg(purchase_amount),2) as avg_purchase_amount
from customer
where shipping_type in ('Express','Standard')
group by shipping_type
-- Conclusion by Express - avg purchase amount=60.48 & by Standard = 58.46


-- Q5. Do subscribed customer spend more?? Compare avg spend and revenue btwn subs vs non-subs

select subscription_status,count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_spend, sum(purchase_amount) as total_revenue
from customer group by subscription_status
-- Conclusion: Non-subscribed customers generate significantly higher total revenue primarily due to their 
-- larger customer base. Additionally, their average  spending is slightly higher than subscribed customers, indicating that the 
-- subscription model is not currently driving higher per-customer spending.


-- Q6. Top 5 products that people like with discount
select item_purchased,round(avg(review_rating),2) as discount_rate from customer
where discount_applied='Yes'
group by item_purchased
order by avg(review_rating) desc
limit 5



-- Q7. Which 5 products need discount help -> highest % of purchase -> discount rate per product? -- 
select item_purchased, round(100* (sum(case when discount_applied='Yes' then 1 else 0 end)/count(*)) ,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5
-- Conclusion: Hat, sneakers,coat,sweater,pants


-- Q8. segment custoners as new, repeating,loyal based of previous purchases
with cte as (
select case
when previous_purchases=1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal' end as segment
 from customer
)
select segment,count(*) as Customer_Count from cte group by segment



-- Q9 What are top 3 products in each category
with cte as (
select category, item_purchased, count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as rn
from customer
group by category,item_purchased
)
select rn as item_rank, category,item_purchased,total_orders from cte 
where rn<=3
group by category,item_purchased



-- Q10  are customers who are repeat buyers likely to subscribe?  ( more than 5 previous previous purchase )

select subscription_status,count(customer_id)
from customer where previous_purchases > 5 group by subscription_status
-- Conclusion: No loyal customers are not subscribers



-- Q11 revenue contribution by each group

select age_group,sum(purchase_amount) as revenue
from customer group by age_group order by revenue desc
-- Conclusion :
-- Young Adult	62143
-- Middle Aged	59197
-- Adult	55978
-- Senior	55763
